### ISSUE TITLE
Problem to get response in pmp module on raspberry pi.

### ISSUE THREAD

**Issue by tukaram-mindstix** [level451/pmp#2]
I was trying to port forward using pmp module. 
It works fine in case of my development machine i.e. it give success or failure according to port forward response, but in case of raspberry pi in show following message instead of success or failure response.
"at pmp portmap function
 ttl:108000 "

**Comment by level451** [comment]
Please post the code that fails thanks

**Comment by tukaram-mindstix** [comment]
var pmp = require('pmp');
pmp.portMap("192.168.1.1",9999,80,1800,function(Error,Response){
	if(Error){
	  console.log("Error : ");	
	  console.log(Error);	
	}
	else{
		console.log("Response : ");
		console.log(Response);
	}
);
Here,
gateway IP = 192.168.1.1
internal port of my device = 80
public Port to be open on server = 54321
TTL = 1800

**Comment by tukaram-mindstix** [comment]
var pmp = require('pmp');
pmp.portMap("192.168.1.1",9999,80,1800,function(Error,Response){
	if(Error){
	  console.log("Error : "+Error);	
	}
	else{
		console.log("Response : "+Response);
	}
);
Here,
gateway IP = 192.168.1.1
internal port of my device = 80
public Port to be open on server = 54321
TTL = 1800

**Comment by tukaram-mindstix** [comment]
var pmp = require('pmp');
pmp.portMap("192.168.1.1",80,54981,1800,function(Error,Response){
    if(Error){
      console.log("Error : "+Error);  
    }
    else{
        console.log("Response : "+Response);
    }
);
where,
gateway IP = 192.168.1.1
internal port of my device = 80
public Port to be open on server = 54981
TTL = 1800

**Comment by level451** [comment]
Try updating in to version .5

and use this code - 

it works for me on the pie 
:)
Todd

   var pmp = require('pmp');

```
pmp.findGateway("",function(err,gateway) {
    if (err) {
        console.log('Gateway not found', err);
    }
    else {
        console.log('gateway found: '+ gateway.ip + ", External IP: "+ gateway.externalIP);

        pmp.portMap(gateway,80,54981,0,'label',function(err,rslt){
            if (err) {
                console.log('error opening port 54981', err);
            }
            else {
               console.log('Port mapped');

            }
        });
    }
});
```

};

**Comment by tukaram-mindstix** [comment]
Thanks :)

On Wed, Apr 8, 2015 at 4:30 AM, level451 notifications@github.com wrote:

> Try updating in to version .5
> 
> and use this code -
> 
> it works for me on the pie
> :)
> Todd
> 
> var pmp = require('pmp');
> 
> pmp.findGateway("",function(err,gateway) {
>     if (err) {
>         console.log('Gateway not found', err);
>     }
>     else {
>         console.log('gateway found: '+ gateway.ip + ", External IP: "+ gateway.externalIP);
> 
> ```
>     pmp.portMap(gateway,80,54981,0,'label',function(err,rslt){
>         if (err) {
>             console.log('error opening port 54981', err);
>         }
>         else {
>            console.log('Port mapped');
> 
>         }
>     });
> }
> ```
> 
> });
> 
> };
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/level451/pmp/issues/2#issuecomment-90753708.

## 

_Tukaram Patil_
MindStix Software Labs
http://www.mindstix.com

Email  : tukaram.patil@mindstix.com
Phone : +91-9767215145
Skype : tukaram.patil7

**Comment by tukaram-mindstix** [comment]
Hi,

  I test pmp module from last 2 days and it's working fine from my side as
well.

Thanks a lot.

On Wed, Apr 8, 2015 at 10:52 AM, Tukaram Patil tukaram.patil@mindstix.com
wrote:

> Thanks :)
> 
> On Wed, Apr 8, 2015 at 4:30 AM, level451 notifications@github.com wrote:
> 
> > Try updating in to version .5
> > 
> > and use this code -
> > 
> > it works for me on the pie
> > :)
> > Todd
> > 
> > var pmp = require('pmp');
> > 
> > pmp.findGateway("",function(err,gateway) {
> >     if (err) {
> >         console.log('Gateway not found', err);
> >     }
> >     else {
> >         console.log('gateway found: '+ gateway.ip + ", External IP: "+ gateway.externalIP);
> > 
> > ```
> >     pmp.portMap(gateway,80,54981,0,'label',function(err,rslt){
> >         if (err) {
> >             console.log('error opening port 54981', err);
> >         }
> >         else {
> >            console.log('Port mapped');
> > 
> >         }
> >     });
> > }
> > ```
> > 
> > });
> > 
> > };
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/level451/pmp/issues/2#issuecomment-90753708.
> 
> ## 
> 
> _Tukaram Patil_
> MindStix Software Labs
> http://www.mindstix.com
> 
> Email  : tukaram.patil@mindstix.com
> Phone : +91-9767215145
> Skype : tukaram.patil7

## 

_Tukaram Patil_
MindStix Software Labs
http://www.mindstix.com

Email  : tukaram.patil@mindstix.com
Phone : +91-9767215145
Skype : tukaram.patil7
